name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set_output.outputs.new_version }}
      version_bumped: ${{ steps.check_bump.outputs.version_bumped }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install bump2version setuptools wheel twine

      - name: Get current version
        id: get_version
        run: echo "::set-output name=current_version::$(python setup.py --version)"

      - name: Bump version
        id: bump_version
        run: |
          if git log -1 --pretty=%B | grep -q 'bump minor'; then
            bump2version minor --current-version ${{ steps.get_version.outputs.current_version }} setup.py
          elif git log -1 --pretty=%B | grep -q 'bump major'; then
            bump2version major --current-version ${{ steps.get_version.outputs.current_version }} setup.py
          else
            echo "No version bump needed"
            echo "::set-output name=new_version::${{ steps.get_version.outputs.current_version }}"

      - name: Set new version output
        id: set_output
        run: echo "::set-output name=new_version::$(python setup.py --version)"

      - name: Check if version bumped
        id: check_bump
        run: |
          if [ "${{ steps.get_version.outputs.current_version }}" != "$(python setup.py --version)" ]; then
            echo "::set-output name=version_bumped::true"
          else
            echo "::set-output name=version_bumped::false"

      - name: Push changes
        if: steps.check_bump.outputs.version_bumped == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git push origin HEAD:main

  build-and-publish:
    needs: bump-version
    if: needs.bump-version.outputs.version_bumped == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ needs.bump-version.outputs.new_version }}
          release_name: Release ${{ needs.bump-version.outputs.new_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to PyPI
        run: |
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
